# Generated by Django 4.2.28 on 2026-02-24 13:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivedWebhook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('razorpay', 'Razorpay'), ('shiprocket', 'Shiprocket'), ('delhivery', 'Delhivery'), ('other', 'Other')], max_length=30)),
                ('event_id', models.CharField(help_text='Unique event ID from the provider — used for idempotency.', max_length=255, unique=True)),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('signature', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('failed', 'Failed')], default='received', max_length=20)),
                ('error_detail', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Received Webhook',
                'verbose_name_plural': 'Received Webhooks',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['event_id'], name='webhooks_re_event_i_822f55_idx'), models.Index(fields=['source', 'event_type'], name='webhooks_re_source_3758f5_idx'), models.Index(fields=['status'], name='webhooks_re_status_520272_idx')],
            },
        ),
    ]
