# Generated by Django 4.2.28 on 2026-02-25 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0002_receivedwebhook'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webhooklog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Webhook Log', 'verbose_name_plural': 'Webhook Logs'},
        ),
        migrations.AddField(
            model_name='webhooklog',
            name='delivery_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='webhooklog',
            name='max_retries',
            field=models.IntegerField(default=3, help_text='Maximum number of delivery attempts.'),
        ),
        migrations.AddField(
            model_name='webhooklog',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='webhookendpoint',
            name='events',
            field=models.JSONField(default=list, help_text='List of events to trigger for (e.g. shipment.status_changed, payment.updated, payout.processed)'),
        ),
        migrations.AlterField(
            model_name='webhooklog',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
    ]
