# Generated by Django 4.2.28 on 2026-03-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='picked_up_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
