# Generated by Django 4.2.28 on 2026-03-11 07:18

import deliveries.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_shipment_picked_up_at'),
        ('tenants', '0001_initial'),
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryattempt',
            options={'ordering': ['attempt_number']},
        ),
        migrations.AddField(
            model_name='deliveryattempt',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude of delivery attempt location.', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='deliveryattempt',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude of delivery attempt location.', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='deliveryattempt',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional driver notes.'),
        ),
        migrations.AddField(
            model_name='deliveryattempt',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to=deliveries.models.signature_upload_path),
        ),
        migrations.AlterField(
            model_name='deliveryattempt',
            name='reason',
            field=models.CharField(blank=True, help_text='Required when status is "failed".', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='deliveryattempt',
            unique_together={('shipment', 'attempt_number')},
        ),
        migrations.CreateModel(
            name='DeliveryConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('max_delivery_attempts', models.PositiveIntegerField(default=3, help_text='Maximum delivery attempts before marking shipment as RTO.')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Delivery Configuration',
                'verbose_name_plural': 'Delivery Configurations',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
